import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Hero from "../components/body/Hero";
import Input from "../components/ui/Input";
import Button from "../components/ui/Button";
import Tool from "../components/tools/Tool";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Toolhub records management</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Hero/>
            <div className="flex flex-col gap-3 justify-center items-center mt-12">
                <Input/>
                <Tool/>
                <div className="flex gap-6 mt-4">
                    <Button type="button" classes="w-44 rounded-sm hover:bg-blue-600 hover:shadow-md h-12 bg-blue-500 text-white">Let's Edit!</Button>
                    <Button type="button" classes="w-44 rounded-sm hover:bg-red-700 hover:shadow-md h-12 bg-red-600 text-white">Skip Tool</Button>
                </div>
                <p className="text-gray-400 mt-3">Number of edits today: 0</p>
            </div>

        </div>
    )
}
