import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Hero from "../components/body/Hero";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Toolhub records management</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Hero/>
            <div className="flex flex-col gap-3 justify-center items-center mt-12">
                <input type="search" className="border border-gray-400 rounded-md mt-4 mb-4 pl-3 w-1/2 h-12" placeholder="Search for a tool"/>
                <div className="w-5/12 text-center">
                    <i className="fas fa-tools text-blue-700 text-6xl"/>
                    <h1 className="mt-4 mb-4 text-3xl">Fixitup tool</h1>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, deserunt eos? Ab alias ducimus et
                        minus quae? Eius facere harum incidunt molestias, nesciunt </p>
                </div>
                <div className="flex gap-6 mt-4">
                    <button type="button" className="w-44 rounded-sm hover:bg-blue-700 hover:shadow-md h-12 bg-blue-600 text-white">Let's Edit!</button>
                    <button type="button" className="w-44 rounded-sm hover:bg-red-700 hover:shadow-md h-12 bg-red-600 text-white">Try something else</button>
                </div>
                <p className="text-gray-400 mt-3">Number of edits today: 0</p>
            </div>

        </div>
    )
}
